import { Jost } from "next/font/google"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jost",
})

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {modal}
        <div className={jost.className}>{children}</div>
      </body>
    </html>
  )
}
